const mockupPosts = [
  {
    id: 1,
    title: "Man vs Machine",
    description: "lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem",
    body: "text",
    author: "Adrian Q",
    date: Date.now().toString(),
    tags: ["technology"],
    likes: 300,
    comments: [
      "comment1",
      "comment2",
      "comment3",
      "comment4",
      "comment5",
      "comment6",
    ],
  },
  {
    id: 2,
    title: "Man vs Machine",
    description: "lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem",
    body: "text",
    author: "Adrian Q",
    date: Date.now().toString(),
    tags: ["technology", ["life"]],
    likes: 20,
    comments: [],
  },
  {
    id: 3,
    title: "Man vs Machine",
    description: "lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem",
    body: "text",
    author: "Adrian Q",
    date: Date.now().toString(),
    tags: ["technology"],
    likes: 290,
    comments: ["comment1", "comment2", "comment3", "comment4", "comment5"],
  },
  {
    id: 4,
    title: "Man vs Machine",
    description: "lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem",
    body: "text",
    author: "Adrian Q",
    date: Date.now().toString(),
    tags: ["technology"],
    likes: 10,
    comments: ["comment1", "comment2"],
  },
  {
    id: 5,
    title: "Man vs Machine",
    description: "lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem",
    body: "text",
    author: "Adrian Q",
    date: Date.now().toString(),
    tags: ["technology"],
    likes: 30,
    comments: ["comment1"],
  },
  {
    id: 6,
    title: "Man vs Machine",
    description: "lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem",
    body: "text",
    author: "Adrian Q",
    date: Date.now().toString(),
    tags: ["technology"],
    likes: 190,
    comments: ["comment1", "comment2", "comment3", "comment4"],
  },
];

export default mockupPosts;
